/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as DronesRouteImport } from './routes/drones'
import { Route as IndexRouteImport } from './routes/index'

const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesRoute = DronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drones': typeof DronesRoute
  '/methodology': typeof MethodologyRoute
  '/results': typeof ResultsRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drones': typeof DronesRoute
  '/methodology': typeof MethodologyRoute
  '/results': typeof ResultsRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drones': typeof DronesRoute
  '/methodology': typeof MethodologyRoute
  '/results': typeof ResultsRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drones' | '/methodology' | '/results' | '/simulation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drones' | '/methodology' | '/results' | '/simulation'
  id: '__root__' | '/' | '/drones' | '/methodology' | '/results' | '/simulation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DronesRoute: typeof DronesRoute
  MethodologyRoute: typeof MethodologyRoute
  ResultsRoute: typeof ResultsRoute
  SimulationRoute: typeof SimulationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones': {
      id: '/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof DronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DronesRoute: DronesRoute,
  MethodologyRoute: MethodologyRoute,
  ResultsRoute: ResultsRoute,
  SimulationRoute: SimulationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
